### ISSUE TITLE
template property not working

### ISSUE THREAD

**Issue by Alfredo-Delgado** [canjs/can-react#1]
This form doesn't seem to be working:

```javascript
export default CanReact.createClass({
  name: 'Component',
  ViewModel,
  template: renderer
});
```

```
Potentially unhandled rejection [1] TypeError: Cannot read property 'bind' of undefined
    at new Component (http://localhost:8080/node_modules/can-react/can-react.js!eval:151:48)
    at ReactCompositeComponentMixin.mountComponent (http://localhost:8080/node_modules/react/lib/ReactCompositeComponent.js:150:18)
    at wrapper [as mountComponent] (http://localhost:8080/node_modules/react/lib/ReactPerf.js:68:21)
    at Object.ReactReconciler.mountComponent (http://localhost:8080/node_modules/react/lib/ReactReconciler.js:39:35)
    at ReactCompositeComponentMixin.mountComponent (http://localhost:8080/node_modules/react/lib/ReactCompositeComponent.js:227:34)
    at wrapper [as mountComponent] (http://localhost:8080/node_modules/react/lib/ReactPerf.js:68:21)
    at Object.ReactReconciler.mountComponent (http://localhost:8080/node_modules/react/lib/ReactReconciler.js:39:35)
    at mountComponentIntoNode (http://localhost:8080/node_modules/react/lib/ReactMount.js:268:32)
    at ReactReconcileTransaction.Mixin.perform (http://localhost:8080/node_modules/react/lib/Transaction.js:138:20)
    at batchedMountComponentIntoNode (http://localhost:8080/node_modules/react/lib/ReactMount.js:284:15)(anonymous function) @ steal.js:140report @ steal.js:167flush @ steal.js:189
```

**Comment by DesignByOnyx** [comment]
This is now fixed in 0.0.4.
